# Site settings
title: spectral bird
description: "random blog"

email: markus.seeber@spectralbird.de
baseurl: ""
url: "http://www.spectralbird.de"
github_username:  mseeber

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /article/:year/:month/:day/
