# Site settings
title: mseeber
email: markus.seeber@spactralbird.de
description: "Markus Seeber"
baseurl: ""
url: "http://sectralbird.de"
twitter_username: amsel
github_username:  mseeber

# Build settings
markdown: kramdown
permalink: pretty
